// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/webhooks/orders-create": {
    params: {};
  };
  "/webhooks/razorpay-test": {
    params: {};
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/api/blend-checkout": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/api/admin/teas": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/sign-in": {
    params: {};
  };
  "/blends": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/webhooks/orders-create" | "/webhooks/razorpay-test" | "/collections/:handle" | "/account/authorize" | "/api/blend-checkout" | "/collections" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/collections/all" | "/policies" | "/account/login" | "/api/admin/teas" | "/discount/:code" | "/pages/:handle" | "/sitemap.xml" | "/blogs" | "/robots.txt" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/sign-in" | "/blends" | "/search" | "/cart" | "/cart/:lines" | "/*";
  };
  "routes/blogs.$blogHandle.$articleHandle.tsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.tsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/webhooks.orders-create.ts": {
    id: "routes/webhooks.orders-create";
    page: "/webhooks/orders-create";
  };
  "routes/webhooks.razorpay-test.ts": {
    id: "routes/webhooks.razorpay-test";
    page: "/webhooks/razorpay-test";
  };
  "routes/collections.$handle.tsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.tsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/api.blend-checkout.ts": {
    id: "routes/api.blend-checkout";
    page: "/api/blend-checkout";
  };
  "routes/collections._index.tsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/policies.$handle.tsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.tsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.tsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/collections.all.tsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/policies._index.tsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/account_.login.tsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/api.admin.teas.ts": {
    id: "routes/api.admin.teas";
    page: "/api/admin/teas";
  };
  "routes/discount.$code.tsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/pages.$handle.tsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/blogs._index.tsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.tsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.tsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.tsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.tsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.tsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/sign-in.tsx": {
    id: "routes/sign-in";
    page: "/sign-in";
  };
  "routes/blends.tsx": {
    id: "routes/blends";
    page: "/blends";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.tsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/blogs.$blogHandle.$articleHandle": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.tsx");
  "routes/sitemap.$type.$page[.xml]": typeof import("./app/routes/sitemap.$type.$page[.xml].tsx");
  "routes/blogs.$blogHandle._index": typeof import("./app/routes/blogs.$blogHandle._index.tsx");
  "routes/webhooks.orders-create": typeof import("./app/routes/webhooks.orders-create.ts");
  "routes/webhooks.razorpay-test": typeof import("./app/routes/webhooks.razorpay-test.ts");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.tsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.tsx");
  "routes/api.blend-checkout": typeof import("./app/routes/api.blend-checkout.ts");
  "routes/collections._index": typeof import("./app/routes/collections._index.tsx");
  "routes/policies.$handle": typeof import("./app/routes/policies.$handle.tsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.tsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.tsx");
  "routes/collections.all": typeof import("./app/routes/collections.all.tsx");
  "routes/policies._index": typeof import("./app/routes/policies._index.tsx");
  "routes/account_.login": typeof import("./app/routes/account_.login.tsx");
  "routes/api.admin.teas": typeof import("./app/routes/api.admin.teas.ts");
  "routes/discount.$code": typeof import("./app/routes/discount.$code.tsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.tsx");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].tsx");
  "routes/blogs._index": typeof import("./app/routes/blogs._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.orders._index": typeof import("./app/routes/account.orders._index.tsx");
  "routes/account.orders.$id": typeof import("./app/routes/account.orders.$id.tsx");
  "routes/account.addresses": typeof import("./app/routes/account.addresses.tsx");
  "routes/account.profile": typeof import("./app/routes/account.profile.tsx");
  "routes/account._index": typeof import("./app/routes/account._index.tsx");
  "routes/account.$": typeof import("./app/routes/account.$.tsx");
  "routes/sign-in": typeof import("./app/routes/sign-in.tsx");
  "routes/blends": typeof import("./app/routes/blends.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/cart.$lines": typeof import("./app/routes/cart.$lines.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};